
platform:
  - x64
branches:
  only:
  - master
clone_depth: 10
environment:
  global:
    MSYSTEM: MSYS
    MBASH: C:\msys64\usr\bin\sh -lc
    PMOPTS: -S --needed --noconfirm --noprogressbar
    REPOFFLIB: >
      \n[fontforgelibs32]\n
      Server = http://downloads.sourceforge.net/project/fontforgebuilds/build-system-extras/fontforgelibs/i686\n
      [fontforgelibs64]\n
      Server = http://downloads.sourceforge.net/project/fontforgebuilds/build-system-extras/fontforgelibs/x86_64\n
  matrix:
    - MINGW_INSTALLS: mingw32
      MBITS: 32
      MPREF: i686
    - MINGW_INSTALLS: mingw64
      MBITS: 64
      MPREF: x86_64
matrix:
  fast_finish: true

#cache:
#  - '%APPVEYOR_BUILD_FOLDER%\msys2.tar.xz -> .appveyor.yml'
#  - '%APPVEYOR_BUILD_FOLDER%\msys64\var\cache\pacman\pkg'
install:
#  - call %MBASH% "pacman-key -r 2E618C78; pacman-key --lsign-key 2E618C78;"
#  - call %MBASH% "echo -e $REPOFFLIB >> /etc/pacman.conf"
  - call %MBASH% "pacman -Syuu --noconfirm"
  - call %MBASH% "pacman -Suu --noconfirm"
  - call %MBASH% "pacman -Suu --noconfirm"
  - call %MBASH% "echo Concurrent build count: $(($(nproc)+1))"
#  - call %MBASH% "pacman $PMOPTS diffutils findutils make patch tar automake autoconf"
#  - call %MBASH% "pacman $PMOPTS mingw-w64-$MPREF-{gcc,libtool}"
#  - call %MBASH% "pacman $PMOPTS mingw-w64-$MPREF-python2"
  - call %MBASH% "rm -rf /mingw$MBITS/include/X11"
  - call %MBASH% "pacman $PMOPTS mingw-w64-$MPREF-freetype"
  - call %MBASH% "pacman -Rdd --noconfirm mingw-w64-$MPREF-cairo || true"
  - call %MBASH% "mkdir -pv `cygpath -u ""$APPVEYOR_BUILD_FOLDER/mingw$MBITS/pkg""`"
  - call %MBASH% "echo 'PACKAGER=""Jeremy Tan <jtanx@outlook.com>""' >> /etc/makepkg_mingw$MBITS.conf"
  - call %MBASH% "echo 'PKGDEST=`cygpath -u ""$APPVEYOR_BUILD_FOLDER/mingw$MBITS/pkg""`' >> /etc/makepkg_mingw$MBITS.conf"
build_script:
  - call %MBASH% "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./build.sh"
  - call %MBASH% "pacman -Sc --noconfirm"
test: off
artifacts:
  - path: mingw$(MBITS)\pkg\*.xz
    name: fontforgelibs$(MBITS)
